### ISSUE TITLE
Duplicate Messages

### ISSUE THREAD

**Issue by hazemtaha** [vincedevendra/firebase_cloud_messenger#21]
i keep getting 2 messages instead of one when I try to send a message using the gem however when i use the console i normally get only 1 message

**Comment by muhammadn** [comment]
@hazemtaha Maybe you have duplicate data (if it is in your database). I found out i had two identical tokens in the database which resulted in two notifications.

**Comment by vincedevendra** [comment]
@hazemtaha it might be best to try to simplify your code down to the simplest possible level--without any other application code, just try manually invoking one of the examples from the README. 

If you're still getting duplicates at that point, feel free to reopen, preferably with the exact code you ran which resulted in the duplicate. Thanks!
